import { openVisibleContent, setAccordeonToggles } from './components/_accordion.js';
import { addFixedHeader } from './components/_fixed-header.js';
import { renderCustomSelect } from './components/_custom-select.js';
import { setMobileMenu } from './components/_open-mobile-menu.js';
import { moveHeader } from './components/_move-header.js';
import { setPopup } from './components/_popup.js';
import { setNavigationSwiper } from './components/_navigation-swiper.js';
import { initCardsSwiper } from './components/_cards-swiper.js';
import { moveHero } from './components/_move-hero.js';
import { setTabs } from './components/_tabs.js';
import { setModals } from './components/_modal.js';
import { setRating } from './components/_rating.js';
import { addScrollButton } from './components/_button-scroll-top.js';
import { setAdvancedSearch } from './components/_advanced-search.js';
import { initCustomScrollbar } from './components/_custom-scrollbar.js';
import { initSelectAllCheckbox } from './components/_checkbox-select-all.js';
import { setDropdown } from './components/_dropdown.js';
import { setFilterToggles } from './components/_filter-view.js';
import { setThumbSwiper } from './components/_thumb-swiper.js';
import { alignGridComponents } from './components/_grid-align.js';
import { setBigTextToggles } from './components/_hide-big-text.js';
import { setCompareSwiper } from './components/_compare-swiper.js';
import { setStickyCards } from './components/_compare-sticky.js';
import { setFancyboxGallery } from './components/_fancybox.js';

document.addEventListener('DOMContentLoaded', () => {
  addFixedHeader();
  renderCustomSelect();
  setMobileMenu();
  moveHeader();
  setPopup();
  setNavigationSwiper();
  initCardsSwiper();
  moveHero();
  setTabs();
  setModals();
  setRating();
  addScrollButton();
  openVisibleContent();
  setAccordeonToggles();
  setAdvancedSearch();
  initCustomScrollbar();
  initSelectAllCheckbox();
  setDropdown();
  setFilterToggles();
  setThumbSwiper();
  alignGridComponents();
  setBigTextToggles();
  setCompareSwiper();
  setStickyCards();
  setFancyboxGallery();
});

